[project]
name = "sdv-generate-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ibis-framework[duckdb]>=10.5.0",
    "jupyter>=1.1.1",
    "sdv>=1.22.1",
    "tqdm>=4.67.1",
]
